const bookData = [
    {
        auteur:"aaaaa",
        titre:"aaaaaaa",
        dateEcriture:1,
        tags:["aaaaaaa"],
        langue:"javanais"
    },
    {
        auteur:"bbbbbb",
        titre:"bbbbbbb",
        dateEcriture:2,
        tags:["bbbbbbbb"],
        langue:"javanais"
    },
    {
        auteur:"ccccc",
        titre:"cccccc",
        dateEcriture:3,
        tags:["cccccc"],
        langue:"javanais"
    },
    {
        auteur:"ddddddd",
        titre:"dddddd",
        dateEcriture:4,
        tags:["ddddddd"],
        langue:"javanais"
    },
    {
        auteur:"eeeeee",
        titre:"eeeeeeee",
        dateEcriture:5,
        tags:["eeeeeee"],
        langue:"javanais"
    },
    {
        auteur:"ffffff",
        titre:"fffffff",
        dateEcriture:6,
        tags:["fffff"],
        langue:"javanais"
    },
    {
        auteur:"gggg",
        titre:"gggg",
        dateEcriture:7,
        tags:["gggggg"],
        langue:"javanais"
    }
]
module.exports.bookData = bookData;